In [ ]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 441 kB 5.1 MB/s 
     |████████████████████████████████| 212 kB 46.4 MB/s 
     |████████████████████████████████| 163 kB 56.1 MB/s 
     |████████████████████████████████| 115 kB 63.5 MB/s 
     |████████████████████████████████| 95 kB 4.6 MB/s 
     |████████████████████████████████| 127 kB 57.5 MB/s 
     |████████████████████████████████| 115 kB 48.9 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: dill
    Found existing installation: dill 0.3.6
    Uninstalling dill-0.3.6:
      Successfully uninstalled dill-0.3.6


In [ ]:
import pandas as pd
import numpy as np
from datasets import load_dataset
import warnings
warnings.filterwarnings('ignore')
dataset = load_dataset("swahili_news")
train_texts = dataset["train"]["text"]
train_labels = dataset["train"]["label"]
test_texts = dataset["test"]["text"]
test_labels = dataset["test"]["label"]
df = pd.DataFrame()
df["text"] = train_texts + test_texts
df["label"] = train_labels + test_labels
df["text"].iloc[np.random.choice(df.index, 100, replace=False)] = np.nan
df = df.sample(np.random.randint(24000, 24500))
df = df.reset_index(drop=True)
print("Your final dataset has have {} rows".format(df.shape[0]))
print("You have the following value counts for the label column:")
print(df["label"].value_counts())


Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/22207 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/7338 [00:00<?, ? examples/s]

Dataset swahili_news downloaded and prepared to /root/.cache/huggingface/datasets/swahili_news/swahili_news/0.2.0/ed5c9a13b97e0d2864ff1e34bfbd38b2f2c54fea77acffcaef187eb4f13cf8cc. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

Your final dataset has have 24257 rows
You have the following value counts for the label column:
1    11041
2     6557
4     2399
3     2031
0     1411
5      818
Name: label, dtype: int64


text  label
0   MAKAMU Mwenyekiti wa Chama Cha Mapinduzi (CCM...      1
1  NA MWALI IBRAHIM, DAR ES SALAAM KOCHA Msaidizi...      2
2   Hayo yalisemwa na Mwenyekiti wa Bodi ya Wakur...      0
3  Mwandishi wetu – Dar es salaam Rais John Maguf...      1
4  *Yatishia kujitoa makundi Kombe la Shirikisho ...      2

In [ ]:
df.head(20)

text  label
0    MAKAMU Mwenyekiti wa Chama Cha Mapinduzi (CCM...      1
1   NA MWALI IBRAHIM, DAR ES SALAAM KOCHA Msaidizi...      2
2    Hayo yalisemwa na Mwenyekiti wa Bodi ya Wakur...      0
3   Mwandishi wetu – Dar es salaam Rais John Maguf...      1
4   *Yatishia kujitoa makundi Kombe la Shirikisho ...      2
5   Mwenyekiti wa Yanga Dkt. Mshindo Msolla, ameth...      2
6    JAJI Mkuu wa Tanzania, Profesa Ibrahimu Juma ...      1
7    MAKAMU wa Rais, Samia Suluhu Hassan amewahaki...      1
8    Kauli hiyo ilitolewa na Mwenyekiti wa Shiriki...      0
9   Mahakama imefuta kesi iliyokuwa inawakabili vi...      1
10  Na FREDRICK KATULANDA-MWANZA  MWILI wa mfanyab...      1
11  \n\tNa KULWA MZEE-DODOMA\n \n\n \n\tMBUNGE wa ...      1
12   Akizungumza na gazeti hili jana, Phiri alisem...      2
13   KOCHA wa zamani wa Gor Mahia na AFC Leopards,...      2
14  NA MWALI IBRAHIM, DAR ES SALAAM WEKUNDU wa Msi...      2
15  \n\tNa MWANDISHI WETU-DAR ES SALAAM\n \n\n \n\...      1
16  Na KULWA MZEE, DAR ES SALAAM Mcheza video, Rut...      4
17   NA MWANDISHI WETU -DAR ES SALAAM TAASISI ya B...      5
18   Na Janeth Mushi, Longido Kijiji cha Leremeta ...      1
19   IKIWA imebaki wiki moja ya kuwasilisha fomu y...      1

In [ ]:
df['text']=df['text'].str.replace('@', '')
df['text']=df['text'].str.replace('*', '')
df['text']=df['text'].str.replace('\d+', '') 
df['text']=df['text'].str.replace('[^\w\s]', '') 
df['text']=df['text'].str.lower()

In [ ]:
df['text'].dropna()

0         makamu mwenyekiti wa chama cha mapinduzi ccm ...
1        na mwali ibrahim dar es salaam kocha msaidizi ...
2         hayo yalisemwa na mwenyekiti wa bodi ya wakur...
3        mwandishi wetu  dar es salaam rais john magufu...
4        yatishia kujitoa makundi kombe la shirikisho k...
                               ...                        
24252     hayo yamesemwa na meneja masoko wa kampuni ya...
24253    chicago marekani ni siku  tangu kim kardashian...
24254     habari zinasema fifa imemwandikia barua karia...
24255     mpango huo unaofahamika kama talent managemen...
24256    east jerusalem palestina      wananchi wa taif...
Name: text, Length: 24174, dtype: object

In [ ]:
df.head(20)

text  label
0    makamu mwenyekiti wa chama cha mapinduzi ccm ...      1
1   na mwali ibrahim dar es salaam kocha msaidizi ...      2
2    hayo yalisemwa na mwenyekiti wa bodi ya wakur...      0
3   mwandishi wetu  dar es salaam rais john magufu...      1
4   yatishia kujitoa makundi kombe la shirikisho k...      2
5   mwenyekiti wa yanga dkt mshindo msolla amethib...      2
6    jaji mkuu wa tanzania profesa ibrahimu juma a...      1
7    makamu wa rais samia suluhu hassan amewahakik...      1
8    kauli hiyo ilitolewa na mwenyekiti wa shiriki...      0
9   mahakama imefuta kesi iliyokuwa inawakabili vi...      1
10  na fredrick katulandamwanza  mwili wa mfanyabi...      1
11  \n\tna kulwa mzeedodoma\n \n\n \n\tmbunge wa k...      1
12   akizungumza na gazeti hili jana phiri alisema...      2
13   kocha wa zamani wa gor mahia na afc leopards ...      2
14  na mwali ibrahim dar es salaam wekundu wa msim...      2
15  \n\tna mwandishi wetudar es salaam\n \n\n \n\t...      1
16  na kulwa mzee dar es salaam mcheza video rutyf...      4
17   na mwandishi wetu dar es salaam taasisi ya bi...      5
18   na janeth mushi longido kijiji cha leremeta k...      1
19   ikiwa imebaki wiki moja ya kuwasilisha fomu y...      1

In [ ]:
sample=df['text'].iloc[11] 
print(sample)


	na kulwa mzeedodoma
 

 
	mbunge wa kawe halima mdee na mbunge wa bunda esther bulaya wote kutoka chadema wamesimamishwa kuhudhuria vikao vyote vya mkutano wa saba wa bunge nane na wa tisa kwa kudharau mamlaka ya spika
 
	kutokana na uamuzi huo wabunge hao hawatahudhuria vikao vya bunge hadi mkutano wa  mwakani katika bunge la bajeti  la aprili 
 
	uamuzi huo ulitolewa jana na bunge baada  ya kukubaliana na hoja ya kubadilisha maazimio ya kamati ya haki maadili na madaraka ya bunge iliyowasilishwa na  mbunge wa viti maalum juliana shonza ccm
 
	kutokana na sakata hilo spika wa bunge job ndugai alisema kikosi cha askari kilichokuwapo bungeni juni  mwaka huu na kushindwa kumtoa nje haraka mbunge wa kibamba john mnyika chadema kimeondolewa na kuletwa kingine kikosi hicho kinadaiwa kilikuwa na askari zaidi ya 
 
	bulaya anatuhumiwa kudharau mamlaka ya spika kwa kukaidi maelekezo yaliyomtaka kutulia kuruhusu mjadala wa
 
	wizara ya nishati na madini uendelee ambapo alionekana akitangatang

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer as cv
vec=cv()
bow=vec.fit_transform(df['text'].values.astype('str'))
from sklearn.model_selection import train_test_split as test

x_train_bow, x_test_bow, y_train_bow, y_test_bow = test(bow, df['label'], test_size=0.2)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier as KN
knn=KN()
knn.fit(x_train_bow, y_train_bow)
bow_pred=knn.predict(x_test_bow)

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_bow, bow_pred)
print(cm)


[[ 153   91   26    6    0    0]
 [ 248 1810  121   36   17   12]
 [  17   59 1176    9   21    0]
 [  22  106   48  221    5    1]
 [  16   61  161    7  233    1]
 [  16  118   11    4    2   17]]


In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test_bow, bow_pred)
print(accuracy)

0.7440230832646332
